spring:
  config:
    import:
     - classpath:kafka-dev.yml
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/mydb?schema=user_resource
    username: spring
    password: boot

  flyway:
    url: jdbc:postgresql://localhost:5433/mydb
    user: spring
    password: boot
    locations: classpath:db/migration
    baseline-on-migrate: true
    enabled: true
    default-schema: user_resource

  data:
    redis:
      host: localhost
      port: 6379
      password: ""

grpc:
  server:
    port: 9091
  client:
    auth-service:
      address: static://localhost:9090
      negotiation-type: plaintext

frontend:
  url: "http://localhost:3000"