spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/mydb
    driver-class-name: org.postgresql.Driver
    username: spring
    password: boot
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
      password: ""

logging:
  level:
    root: debug

grpc:
  server:
    port: 9091
  client:
    auth-service:
      address: static://localhost:9090
      negotiation-type: plaintext
