spring:
  config:
    import:
     - classpath:kafka-dev.yml
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/mydb?schema=projection
    username: spring
    password: boot

  flyway:
    url: jdbc:postgresql://localhost:5433/mydb
    user: spring
    password: boot
    locations: classpath:db/migration
    baseline-on-migrate: true
    enabled: true
    default-schema: projection

  data:
    redis:
      host: localhost
      port: 6379
      password: ""

meilisearch:
  url: http://localhost:7700
  api-key: Uyflv5mWWF3Apyp23PhvAPyFpVnJB6CC_coToMPFcrk