spring:
  application:
    name: article-query
  profiles:
    active: dev
  config:
    import: application-secret.yml
  graphql:
    graphiql:
      enabled: true

server:
  forward-headers-strategy: framework
  port: 8083
