spring:
  #  datasource:
  #    url: jdbc:postgresql://localhost:5433/mydb
  #    driver-class-name: org.postgresql.Driver
  #    username: spring
  #    password: boot
  #  jpa:
  #    hibernate:
  #      ddl-auto: update
  #    properties:
  #      hibernate:
  #        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  data:
    redis:
      host: localhost
      port: 6379
      password: ""


logging:
  level:
    org.springframework.context: DEBUG
    org.springframework.data.neo4j: DEBUG
    org.springframework.security: DEBUG

grpc:
  server:
    port: 9090
  client:
    user-service:
      address: static://localhost:9091
      negotiation-type: plaintext
