spring:
  config:
    import: 'classpath:infra-kafka-application.yml'
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/mydb
    username: spring
    password: boot
  data:
    redis:
      host: localhost
      port: 6379
      password: ""
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: codeswamp

logging:
  level:
    org.springframework.context: DEBUG
    org.springframework.data.neo4j: DEBUG
    org.springframework.security: DEBUG

server:
  servlet:
    context-path: /api

frontend:
  url: "http://localhost:3000"