spring:
  config:
    import:
     - classpath:kafka-dev.yml
     - classpath:outbox-dev.yml

  r2dbc:
    url: r2dbc:postgresql://localhost:5433/mydb
    username: spring
    password: boot

  flyway:
    url: jdbc:postgresql://localhost:5433/mydb
    user: spring
    password: boot
    locations: classpath:db/migration
    baseline-on-migrate: true
    enabled: true

  data:
    redis:
      host: localhost
      port: 6379
      password: ""
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: codeswamp


logging:
  level:
    org.springframework.context: DEBUG
    org.springframework.data.r2dbc: DEBUG
    org.springframework.data.neo4j: DEBUG
    io.r2dbc: DEBUG

frontend:
  url: "http://localhost:3000"